// <auto-generated />
namespace WebApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Urunler_duzenleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Urunler_duzenleme));
        
        string IMigrationMetadata.Id
        {
            get { return "201711301555563_Urunler_duzenleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
