//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnaSayfa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnaSayfa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.AnaSayfa", typeof(AnaSayfa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamı için tıklayın.
        /// </summary>
        public static string DevamiIcinTikla {
            get {
                return ResourceManager.GetString("DevamiIcinTikla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını okuyun....
        /// </summary>
        public static string DevaminiOku {
            get {
                return ResourceManager.GetString("DevaminiOku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merak Edilenler.
        /// </summary>
        public static string MerakEdilenler {
            get {
                return ResourceManager.GetString("MerakEdilenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Gelişmeler.
        /// </summary>
        public static string SonGelismeler {
            get {
                return ResourceManager.GetString("SonGelismeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogdaki son gelişmelerden haberiniz olsun. Takipte Kalın....
        /// </summary>
        public static string SonGelismelerHaberinizOlsun {
            get {
                return ResourceManager.GetString("SonGelismelerHaberinizOlsun", resourceCulture);
            }
        }
    }
}
