//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BizeUlasin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BizeUlasin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.BizeUlasin", typeof(BizeUlasin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize ulasin.
        /// </summary>
        public static string bizeUlasin {
            get {
                return ResourceManager.GetString("bizeUlasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        public static string destek {
            get {
                return ResourceManager.GetString("destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haşim Gürdamar Bilgisayar ve Bilişim Fakültesi.
        /// </summary>
        public static string hasimGurdamarBilgBilisimFakultesi {
            get {
                return ResourceManager.GetString("hasimGurdamarBilgBilisimFakultesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletmek İstedikleriniz.
        /// </summary>
        public static string iletmekIstedikleriniz {
            get {
                return ResourceManager.GetString("iletmekIstedikleriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gönder.
        /// </summary>
        public static string mesajGonder {
            get {
                return ResourceManager.GetString("mesajGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİZE NASIL YARDIMICI OLABİLİRİZ?.
        /// </summary>
        public static string nasilYardimciOlabiliriz {
            get {
                return ResourceManager.GetString("nasilYardimciOlabiliriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya Üniversitesi.
        /// </summary>
        public static string sakaryaUniversitesi {
            get {
                return ResourceManager.GetString("sakaryaUniversitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler mesajınız iletilmiştir.
        /// </summary>
        public static string tesekkurMesaj {
            get {
                return ResourceManager.GetString("tesekkurMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üniversite.
        /// </summary>
        public static string universite {
            get {
                return ResourceManager.GetString("universite", resourceCulture);
            }
        }
    }
}
