//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlogEkle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogEkle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.BlogEkle", typeof(BlogEkle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık giriniz.
        /// </summary>
        public static string baslikGiriniz {
            get {
                return ResourceManager.GetString("baslikGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Başlığı.
        /// </summary>
        public static string blogBasligi {
            get {
                return ResourceManager.GetString("blogBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog İçeriği.
        /// </summary>
        public static string blogIcerik {
            get {
                return ResourceManager.GetString("blogIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik giriniz.
        /// </summary>
        public static string icerikGir {
            get {
                return ResourceManager.GetString("icerikGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yolu.
        /// </summary>
        public static string resimYol {
            get {
                return ResourceManager.GetString("resimYol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim yolu giriniz.
        /// </summary>
        public static string resimYolGir {
            get {
                return ResourceManager.GetString("resimYolGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog yazınız yayınlanmıştır..
        /// </summary>
        public static string talepBasarili {
            get {
                return ResourceManager.GetString("talepBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string talepGonder {
            get {
                return ResourceManager.GetString("talepGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Yazısı Yayınla.
        /// </summary>
        public static string talepGonderBaslik {
            get {
                return ResourceManager.GetString("talepGonderBaslik", resourceCulture);
            }
        }
    }
}
