//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DersNotu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DersNotu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.DersNotu", typeof(DersNotu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TALEP GÖNDER.
        /// </summary>
        public static string buton {
            get {
                return ResourceManager.GetString("buton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Adı:.
        /// </summary>
        public static string dersAdi {
            get {
                return ResourceManager.GetString("dersAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS NOTU EKLEME TALEBİ.
        /// </summary>
        public static string dersNotEklemeTalep {
            get {
                return ResourceManager.GetString("dersNotEklemeTalep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS NOTLARI.
        /// </summary>
        public static string dersnotlari {
            get {
                return ResourceManager.GetString("dersnotlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Notu Açıklama.
        /// </summary>
        public static string dersNotuAciklama {
            get {
                return ResourceManager.GetString("dersNotuAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Notu Resmi.
        /// </summary>
        public static string dersNotuResim {
            get {
                return ResourceManager.GetString("dersNotuResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik talebiniz alınmıştır. Onaylandığı zaman yayınlanacaktır..
        /// </summary>
        public static string etkinlikTalepAlindi {
            get {
                return ResourceManager.GetString("etkinlikTalepAlindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangi Konuda Yardım Almak İstediginizi Bize İletiniz...
        /// </summary>
        public static string hangiKonu {
            get {
                return ResourceManager.GetString("hangiKonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu Başlığı.
        /// </summary>
        public static string konuBasligi {
            get {
                return ResourceManager.GetString("konuBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz onay bekliyor.
        /// </summary>
        public static string onayBekliyor {
            get {
                return ResourceManager.GetString("onayBekliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz onaylandı.
        /// </summary>
        public static string onaylandi {
            get {
                return ResourceManager.GetString("onaylandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biriktirdiğin değil.
        /// </summary>
        public static string overlay1 {
            get {
                return ResourceManager.GetString("overlay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaştığın.
        /// </summary>
        public static string overlay2 {
            get {
                return ResourceManager.GetString("overlay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senindir.
        /// </summary>
        public static string overlay3 {
            get {
                return ResourceManager.GetString("overlay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaşan Kullanıcı.
        /// </summary>
        public static string paylasan {
            get {
                return ResourceManager.GetString("paylasan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz reddedildi.
        /// </summary>
        public static string reddedildi {
            get {
                return ResourceManager.GetString("reddedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
    }
}
