//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Esya {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Esya() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.Esya", typeof(Esya).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        public static string diger {
            get {
                return ResourceManager.GetString("diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronik.
        /// </summary>
        public static string elektronik {
            get {
                return ResourceManager.GetString("elektronik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitap.
        /// </summary>
        public static string kitap {
            get {
                return ResourceManager.GetString("kitap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıyafet.
        /// </summary>
        public static string kiyafet {
            get {
                return ResourceManager.GetString("kiyafet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilya.
        /// </summary>
        public static string mobilya {
            get {
                return ResourceManager.GetString("mobilya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. El.
        /// </summary>
        public static string overlay1 {
            get {
                return ResourceManager.GetString("overlay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşyalar.
        /// </summary>
        public static string overlay2 {
            get {
                return ResourceManager.GetString("overlay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle.
        /// </summary>
        public static string sepeteEkle {
            get {
                return ResourceManager.GetString("sepeteEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Eklenenler.
        /// </summary>
        public static string sonEklenenler {
            get {
                return ResourceManager.GetString("sonEklenenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Açıklaması.
        /// </summary>
        public static string urunAciklamasi {
            get {
                return ResourceManager.GetString("urunAciklamasi", resourceCulture);
            }
        }
    }
}
