//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Etkinlikler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Etkinlikler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.Etkinlikler", typeof(Etkinlikler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Onay Bekliyor.
        /// </summary>
        public static string bekliyor {
            get {
                return ResourceManager.GetString("bekliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş.
        /// </summary>
        public static string bitis {
            get {
                return ResourceManager.GetString("bitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlikten Çık.
        /// </summary>
        public static string cik {
            get {
                return ResourceManager.GetString("cik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Ekleme Talebi.
        /// </summary>
        public static string eklemeTalep {
            get {
                return ResourceManager.GetString("eklemeTalep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinik Açıklama.
        /// </summary>
        public static string etkAciklama {
            get {
                return ResourceManager.GetString("etkAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Adi.
        /// </summary>
        public static string etkAdi {
            get {
                return ResourceManager.GetString("etkAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Yapılacağı Adres.
        /// </summary>
        public static string etkAdres {
            get {
                return ResourceManager.GetString("etkAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Başlama Tarihi.
        /// </summary>
        public static string etkBaslangic {
            get {
                return ResourceManager.GetString("etkBaslangic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Bitiş Tarihi.
        /// </summary>
        public static string etkBitis {
            get {
                return ResourceManager.GetString("etkBitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Resmi.
        /// </summary>
        public static string etkResim {
            get {
                return ResourceManager.GetString("etkResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talep Gönder.
        /// </summary>
        public static string gonder {
            get {
                return ResourceManager.GetString("gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Ekleme Talebi Gönder.
        /// </summary>
        public static string gonderBaslik {
            get {
                return ResourceManager.GetString("gonderBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangi Konuda Yardım Almak İstediginizi Bize İletiniz...
        /// </summary>
        public static string hangiKonuda {
            get {
                return ResourceManager.GetString("hangiKonuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinliğe Katıl.
        /// </summary>
        public static string katil {
            get {
                return ResourceManager.GetString("katil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Sahibi Kulüp İsmi.
        /// </summary>
        public static string kulupIsmi {
            get {
                return ResourceManager.GetString("kulupIsmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Onaylandı.
        /// </summary>
        public static string onaylandi {
            get {
                return ResourceManager.GetString("onaylandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Etkinlikte.
        /// </summary>
        public static string overlay1 {
            get {
                return ResourceManager.GetString("overlay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben De.
        /// </summary>
        public static string overlay2 {
            get {
                return ResourceManager.GetString("overlay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varım.
        /// </summary>
        public static string overlay3 {
            get {
                return ResourceManager.GetString("overlay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Reddedildi.
        /// </summary>
        public static string reddedildi {
            get {
                return ResourceManager.GetString("reddedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teşekkürler. Talebiniz gönderilmiştir..
        /// </summary>
        public static string tesekkurlerBasarili {
            get {
                return ResourceManager.GetString("tesekkurlerBasarili", resourceCulture);
            }
        }
    }
}
