//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp2.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string Adiniz {
            get {
                return ResourceManager.GetString("Adiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres :Sakarya Üniversitesi Haşim Gürdamar Bilgisayar ve Bilişim Fakültesi.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileri Doldurunuz.
        /// </summary>
        public static string bilgileriDoldurunuz {
            get {
                return ResourceManager.GetString("bilgileriDoldurunuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize-Ulaşın.
        /// </summary>
        public static string bizeUlasin {
            get {
                return ResourceManager.GetString("bizeUlasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Notu / Soru Paylaşımı.
        /// </summary>
        public static string dersNotSoruPaylasimi {
            get {
                return ResourceManager.GetString("dersNotSoruPaylasimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinliğe Katıl.
        /// </summary>
        public static string etkinligeKatil {
            get {
                return ResourceManager.GetString("etkinligeKatil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlikler.
        /// </summary>
        public static string Etkinlikler {
            get {
                return ResourceManager.GetString("Etkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlige Katılmak İcin Şifrenizi Giriniz.
        /// </summary>
        public static string etkinlikSifreGir {
            get {
                return ResourceManager.GetString("etkinlikSifreGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string girisYap {
            get {
                return ResourceManager.GetString("girisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string Hosgeldiniz {
            get {
                return ResourceManager.GetString("Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkinci El Eşyalar.
        /// </summary>
        public static string ikinciElEsya {
            get {
                return ResourceManager.GetString("ikinciElEsya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Kaydı / Giriş.
        /// </summary>
        public static string kayitGiris {
            get {
                return ResourceManager.GetString("kayitGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolamı unuttum.
        /// </summary>
        public static string ParolamiUnuttum {
            get {
                return ResourceManager.GetString("ParolamiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya Üniversitesi.
        /// </summary>
        public static string sakaryaUniversitesi {
            get {
                return ResourceManager.GetString("sakaryaUniversitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAÜ Tanıtım.
        /// </summary>
        public static string sauTanitim {
            get {
                return ResourceManager.GetString("sauTanitim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        public static string sifreniz {
            get {
                return ResourceManager.GetString("sifreniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin İçin Seçtiklerimiz.
        /// </summary>
        public static string sizeSectiklerimiz {
            get {
                return ResourceManager.GetString("sizeSectiklerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Tweetler.
        /// </summary>
        public static string SonTweet {
            get {
                return ResourceManager.GetString("SonTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        public static string Soyadiniz {
            get {
                return ResourceManager.GetString("Soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Şifreniz.
        /// </summary>
        public static string TekrarSifreniz {
            get {
                return ResourceManager.GetString("TekrarSifreniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string uyeOl {
            get {
                return ResourceManager.GetString("uyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ol veya Giriş yap.
        /// </summary>
        public static string uyeOlGirisYap {
            get {
                return ResourceManager.GetString("uyeOlGirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten üye misiniz? Giriş yapın.
        /// </summary>
        public static string zatenUyeMisin {
            get {
                return ResourceManager.GetString("zatenUyeMisin", resourceCulture);
            }
        }
    }
}
